.\"Created with GNOME Manpages Editor
.\"http://sourceforge.net/projects/gmanedit2

.\"Replace <program> with the program name, x with the Section Number
.TH bin2header 1 "Sep 21, 2017" "bin2header-0.1.0" "Binary to header converter"

.SH NAME
bin2header \- Binary to header

.SH USAGE
.B bin2header
.RI <file>
.br

.SH SYNOPSIS
Convert a binary file into a C/C++ header.

.SH DESCRIPTION
bin2header takes any file as an argument and converts its binary data into a source header file for use in C/C++ applications. The data is stored as a character array.