.\"Created with GNOME Manpages Editor
.\"http://sourceforge.net/projects/gmanedit2

.TH bin2header 1 "Aug 6, 2022" "bin2header-0.2.0"

.SH NAME
Binary to Header

.SH SYNOPSIS
.B bin2header
.RI [options]
.RI file
.br

.SH OPTIONS
.TP
.BR \-h ", " \-\-help
Print help information & exit.
.TP
.BR \-v ", " \-\-version
Print version information & exit.
.TP
.BR \-o ", " \-\-output
Set output file name.
.TP
.BR \-n ", " \-\-hname
Set header name.
.TP
.BR \-s ", " \-\-chunksize
Set the buffer chunk size (in bytes).
.br
Default: 1048576 (1 megabyte)
.TP
.BR \-d ", " \-\-nbdata
Set number of bytes per line.
.br
Default: 12
.TP
.BR \-c ", " \-\-datacontent
Show data content as comment.
.TP
.BR \-f ", " \-\-offset
Start reading at given offset from file beginning.
.TP
.BR \-l ", " \-\-length
Number of bytes to process.
.TP
.BR \-p ", " \-\-pack
Store data using 8, 16, or 32 bit integer types.
.br
Default: 8
.TP
.BR \-e ", " \-\-swap
Swap endianess for 16 or 32 bit integer types.
.TP
.BR \-\-stdvector
Additionally store data in std::vector for C++.

.SH DESCRIPTION
bin2header takes any file as an argument and converts its binary data into a source header file for use in C/C++ applications. The data is stored as a character array.
