
name: Check Program Output

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build native executable
        run: |
          mkdir -p build/native/
          cd build/native/
          cmake ../../
          cmake --build ./

      - name: Run tests with native
        run: |
          cd tests/
          cp ../build/native/bin2header ./
          ./check_output.sh
          rm ./bin2header

      - name: Build Python executable
        run: |
          mkdir -p build/python/
          cd build/python/
          cmake -DNATIVE=OFF ../../
          cmake --build ./

      - name: Run tests with Python
        run: |
          cd tests/
          cp ../build/python/bin2header.py ./bin2header
          chmod +x ./bin2header
          ./check_output.sh
