
name: Build GitHub Pages

on:
  push:
    branches: [ master ]
    paths:
      - 'docs/**'
  workflow_dispatch:

jobs:
  build-page:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: 'docs/'
