
name: Check Python Code

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**.py'
  pull_request:
  workflow_dispatch:

jobs:
  python-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pylint action
        uses: gabriel-milan/action-pylint@v1
        id: pylint
        with:
          path: "src/*.py"

      - name: Mypy action
        uses: jashparekh/mypy-action@v3
        id: mypy
        with:
          path: "src/*.py"
          # documentation from jashparekh/mypy-action appears to be incorrect
          #mypy_flags: '--allow-untyped-globals'
          mypy_options: '--allow-untyped-globals'
