
name: Check C/C++ Code

on:
  push:
    branches: [ master ]
    paths:
      - 'src/**.c'
      - 'src/**.cpp'
      - 'src/**.h'
      - 'src/**.hpp'
  pull_request:
  workflow_dispatch:

jobs:
  cpp-linter:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup cppcheck
        run: sudo apt install cppcheck

      - name: Analyze C++ code
        run: |
          cppcheck --error-exitcode=1 --std=c++11 \
            --enable=style,performance,portability,missingInclude \
            --suppress=\*:src/include/cxxopts.hpp \
            --suppress=preprocessorErrorDirective:src/include/cxxopts.hpp \
            --suppress=passedByValue \
            --suppress=missingIncludeSystem \
            -I src/include/ \
            src/
