
# creates 32 & 64 bit builds for Windows

name: PE32 Builds

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build dependencies
        run: sudo apt install mingw-w64 cmake

      - name: Compile 64-bit
        run: |
          mkdir -p builds/win64/stage/bin2header/ && cd builds/win64
          cmake -G "Unix Makefiles" \
            -DCMAKE_TOOLCHAIN_FILE=cmake/mingw-w64-x86_64.cmake \
            -DCMAKE_INSTALL_PREFIX="$(pwd)/install/bin2header/" \
            -DSTATIC=ON \
            -DEMBED_ICON=ON \
            ../../
          cmake --build ./
          cp bin2header.exe stage/bin2header/
          cp ../../LICENSE.txt stage/bin2header/

      - name: Compile 32-bit
        run: |
          mkdir -p builds/win32/stage/bin2header/ && cd builds/win32
          cmake -G "Unix Makefiles" \
            -DCMAKE_TOOLCHAIN_FILE=cmake/mingw-w64-i686.cmake \
            -DCMAKE_INSTALL_PREFIX="$(pwd)/install/bin2header/" \
            -DSTATIC=ON \
            -DEMBED_ICON=ON \
            ../../
          cmake --build ./
          cp bin2header.exe stage/bin2header/
          cp ../../LICENSE.txt stage/bin2header/

      # - name: Package
        # run: |
          # VERSION="$(grep "^VERSION=" info.cfg | sed -e 's/^VERSION=//')"
          # zip builds/bin2header_${VERSION}_win64.zip builds/win64/bin2header.exe LICENSE.txt
          # zip builds/bin2header_${VERSION}_win32.zip builds/win32/bin2header.exe LICENSE.txt

      - name: Upload 64-bit
        uses: actions/upload-artifact@v3
        with:
          name: bin2header_win64
          path: builds/win64/stage/bin2header/*

      - name: Upload 32-bit
        uses: actions/upload-artifact@v3
        with:
          name: bin2header_win32
          path: builds/win32/stage/bin2header/*
