
name: Publish Release

on:
  push:
    tags:
      - 'v[0-9]*'

jobs:
  main:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up build dependencies
        run: sudo apt install mingw-w64 cmake

      - name: Compile 64-bit
        run: |
          mkdir -p builds/win64/stage/ && cd builds/win64
          cmake -G "Unix Makefiles" \
            -DCMAKE_TOOLCHAIN_FILE=cmake/mingw-w64-x86_64.cmake \
            -DSTATIC=ON \
            -DEMBED_ICON=ON \
            ../../
          cmake --build ./
          cp bin2header.exe stage/
          cp ../../LICENSE.txt stage/

      - name: Package 64-bit
        run: |
          pwd
          cd builds/win64/stage/
          zip ../../bin2header-$(grep "^VERSION=" ../../../info.cfg | sed -e 's/^VERSION=//')-win64.zip *

      - name: Compile 32-bit
        run: |
          mkdir -p builds/win32/stage/ && cd builds/win32
          cmake -G "Unix Makefiles" \
            -DCMAKE_TOOLCHAIN_FILE=cmake/mingw-w64-i686.cmake \
            -DSTATIC=ON \
            -DEMBED_ICON=ON \
            ../../
          cmake --build ./
          cp bin2header.exe stage/
          cp ../../LICENSE.txt stage/

      - name: Package 32-bit
        run: |
          cd builds/win32/stage/
          zip ../../bin2header-$(grep "^VERSION=" ../../../info.cfg | sed -e 's/^VERSION=//')-win32.zip *

      - name: Package Python
        run: |
          mkdir -p builds/python/stage/
          cp src/bin2header.py builds/python/stage/
          cp LICENSE.txt builds/python/stage/
          cd builds/python/stage/
          PYVERSION="$(grep "^PYVERSION=" ../../../info.cfg | sed -e 's/^PYVERSION=//')"
          TARFILE="../../bin2header-${PYVERSION}-python.tar"
          tar -cf "${TARFILE}" --mode=0755 bin2header.py
          tar -uf "${TARFILE}" LICENSE.txt
          xz -z9 "${TARFILE}"

      - name: Package source
        run: ./scripts/dist.sh

      - name: Get changes
        run: sed -e '/^$/,$d' -e '1 s/^.*$/Changes:\n/' CHANGES.txt > release_notes.tmp

      - name: Publish
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body_path: release_notes.tmp
          files: |
            bin2header-*.tar.xz
            builds/bin2header-*.zip
            builds/bin2header-*-python.tar.xz
          prerelease: true
